### ISSUE TITLE
Investigate counter write wear-leveling

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-fido2-firmware#1]
Investigate whether counter use write wear-leveling, specifically:
- its estimated lifetime;
- whether it would be worth to use more space for it;
- are there any weak points in the implementation.

See: 
https://github.com/Nitrokey/nitrokey-fido2-firmware/blob/dd4ff920adba03e5eb92a99add667a3d63fc3d22/targets/stm32l432/src/device.c#L354

**Comment by jans23** [comment]
Perhaps we could utilise the logic for HOTP's counter in Nitrokey Pro.

**Comment by szszszsz** [comment]
Main counter page is wear-leveled. There is a place for improvement, but it is redundant in this use-scale. 

Namely `COUNTER2` page is not wear-leveled, and it is written every 256 increments of the counter. However it seems there is no need for that.

https://github.com/Nitrokey/nitrokey-fido2-firmware/blob/dd4ff920adba03e5eb92a99add667a3d63fc3d22/targets/stm32l432/src/device.c#L412

Given 10k flash page endurance, it should suffice for about 2.5M (256*10k) increments over device's lifetime, which is:
- 701 per day over 10 years;
- 233 per day over 30 years;

which is far over expected use (10-30 per day).

Reference table for internal flash characteristics: https://www.st.com/resource/en/datasheet/stm32l432kc.pdf - page 103, 6.3.10 Electrical characteristics / Flash memory characteristics, table 51. Flash memory endurance and data retention
