### ISSUE TITLE
Change LED behaviour to that of NK FIDO U2F

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-fido2-firmware#10]
Currently when the device is connected the LED shines 90% of the time and sometimes goes off. Also in active mode, blinking frequency is different than NK FIDO U2F. The goal is to make blinking similarly to NK FIDO U2F. For new FIDO2-specific states, behaviour of Yubikey could be considered too.

These states (and potentially more) should be checked:
- device start
- idle
- registration request
- authentication request
- expired requests?
- firmware update?
- button press

**Comment by jans23** [comment]
Because of [this issue](https://github.com/Nitrokey/nitro-python/issues/1) I couldn't test all use cases. But what I see so far:

- I suggest to have a short blink during device start, similarly to Nitrokey Pro and FIDO U2F. This allows to identify faulty devices easily (without involving a potential client software issue).
- The blinking during registration, authentication and other commands should be slightly improved. Right now its frequency between off and on is not entirely balanced. Also it seems to sometimes blink faster and sometimes slower (during the same operation). Instead it should blink exactly like the FIDO U2F.
- Wink should blink longer, like Nitrokey FIDO U2F (ca. 5 seconds). Using a frequency other than for "ordinary" FIDO commands is good to allow distinguishing them.

I would like to test a firmware update too. All other actions look good to me.

**Comment by szszszsz** [comment]
Current behavior:

|  Event  |     LED behavior      |
|:--------|:-------------|
| device start |  single blink after 2 seconds |
| idle |    off   |
| registration request | standard blinking |
| authentication request | standard blinking |
| touch consumed | green LED active |
| expired requests | off |
| firmware update | standard blinking |
| button press | no influence |
| bootloader active | all colors sequentially |
