### ISSUE TITLE
Merge latest code from upstream

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-fido2-firmware#12]

**Comment by szszszsz** [comment]
We are almost par to the current upstream. Current version: `2.4.2`. Leaving to check once again before milestone is closed.

**Comment by szszszsz** [comment]
Current version is `2.4.3`. Lately stable `2.5.1` was released in the upstream.

**Comment by szszszsz** [comment]
Fixed with merge of upstream/3.0.0: d6f29f92c5a459314712e1fe57ba8ae9a86c3bc5.
Closing as done.
