### ISSUE TITLE
How is device key generated?

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-fido2-firmware#13]

**Comment by szszszsz** [comment]
Device key (`STATE.key_space`) is generated in the `ctap_state_init()` function, using the hardware's RNG. 
The `STATE.key_space` variable is really an undefined structure holding `uint8_t master_key [64]`, and `uint8_t transport_key [32]`, used inside the code like here:
https://github.com/Nitrokey/nitrokey-fido2-firmware/blob/master/fido2/crypto.c#L80-L87

Mentioned function definition for initialization is:
https://github.com/Nitrokey/nitrokey-fido2-firmware/blob/master/fido2/ctap.c#L1700-L1713

It is called during the very first power-up of the device, and on the subsequent FIDO2 resets. FIDO U2F uses the same secret.

CTAP reset:
https://github.com/Nitrokey/nitrokey-fido2-firmware/blob/master/fido2/ctap.c#L1975-L1980

The very first power-up:
https://github.com/Nitrokey/nitrokey-fido2-firmware/blob/master/fido2/ctap.c#L1715-L1741

Closing as reviewed.
