### ISSUE TITLE
Timeout during web update

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-fido2-firmware#40]
User reported that during the web update one of the requests timed out.
OS: Windows 10 2004
Browser: Firefox 77 (latest at the time of issue occurrence)

![image](https://user-images.githubusercontent.com/17005426/86355221-a3ddd180-bc6a-11ea-8cd2-d1178760bf53.png)

Second attempt, successful:
Windows 10 2004, Firefox Nightly (no version - probably 79 or 80)

Details:
> The update started.
The first line progress bar was finished.
There was always a Security hint from the operating system to authenticate. The only option was/is cancel.
As the first update bar was finished nothing else happened and after a while a timeout error was reported.
A second attempt ended in the same scenario.
When I plug the FIDO2 now to the PC there is no message giving feedback about the device.
---later-------
> The update ran through on a 32 bit machine with windows 10 and Firefox Nightly Version.
I am not sure what was blocking the process.
Anyway the update to 2.0 was conducted.

Connected: https://support.nitrokey.com/t/firmware-update-fido2-to-2-0-failed-does-not-work/2450/1

**Comment by jans23** [comment]
Which browser and version was used for the first attempt?

**Comment by szszszsz** [comment]
Firefox 77 (latest at that time). Updated description.

**Comment by szszszsz** [comment]
Most probably this was caused by the Windows 10. Fixed in the Webupdate.
Closing as invalid.
