### ISSUE TITLE
Describe behavior change

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-fido2-firmware#57]
Document behavior change introduced in v2.1:
- [x] LED colors;
- [x] touch button required time for different operations;
- [x] added touch confirmation for the bootloader;

**Comment by jans23** [comment]
I suggest to document this latest behaviour in docs.nitrokey.com

**Comment by szszszsz** [comment]
Published to:
- https://docs.nitrokey.com/fido2/windows/#touch-button-and-led-behavior

To add the same to Linux and macOS OSes, if not automatically pushed.
