### ISSUE TITLE
Test user data retention

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-fido2-firmware#6]
- [x] Test empirically, whether user data stay in place after the firmware update.
- [x] Check, how ctap_reset influences user data.
- [x] See, if there is a factory-reset equivalent for clearing user secrets / overwriting with new secrets.
- [x] Analyse if attestation key survives firmware updates

**Comment by jans23** [comment]
- [ ] Analyse if attestation key survives firmware updates

**Comment by szszszsz** [comment]
AFAIR the attestation key is provided as a binary blob inside the each firmware. Perhaps linking script is moving it to a specific place - to check. Would be nice to make a flash memory map for user data and device secrets.

**Comment by jans23** [comment]
This implicates that firmware updates shouldn't just be signed but also encrypted. If this is the case, which key is used for encryptio/decryption and how is it secured?

**Comment by szszszsz** [comment]
Attestation key is added during the complete firmware (`all.hex`) generation stage, which is written during the initial devices' production. It lives on page `-15`. Update firmware binaries do not contain the key, neither bootloader can ever update it (as it is outside of the updateable 'application' region).

CTAP reset operation clears the user's secret, which is a factory-reset.

**Comment by szszszsz** [comment]
Closing as done.
