### ISSUE TITLE
Edge browser no longer supported?

### ISSUE THREAD

**Issue by beerisgood** [Nitrokey/nitrokey-fido2-firmware#62]
![image](https://user-images.githubusercontent.com/9625159/105495244-39e75100-5cbc-11eb-8ab1-94b185c2489c.png)

where is the expert option to enforce the browser?

Edit: Ups. Found at bottom right.

**Comment by beerisgood** [comment]
a How-to like in https://github.com/Nitrokey/nitrokey-webupdate/issues/15#issuecomment-699899029 need to be pinned somewhere.

**Comment by szszszsz** [comment]
Hi @beerisgood !

Sorry for the confusion. I was sure we have corrected the update description in the UI already. Will check.
I understand that the part about keeping the touch longer is missing, is that right?

Regarding forcing the browser update - I can add a sentence about how to force running the update on the current browser, which I believe would be handy.

Transferring ticket to proper project. Recognized as an UI issue of Web Update application.
